### ISSUE TITLE
new v1.0 release

### ISSUE THREAD

**Issue by fkooman** [paragonie/constant_time_encoding#14]
Would it be possible to release v1.0.2 with the fixes queued in the v1.x branch? I'm looking forward to be able to consistently catch `\RangeException` on decode failures.

**Comment by paragonie-scott** [comment]
Sure, just be aware that when PHP 5 reaches EOL later this year, we'll no longer be supporting PHP 5.

**Comment by fkooman** [comment]
Fair enough, thanks!
