### ISSUE TITLE
Base64 is malleable

### ISSUE THREAD

**Issue by fkooman** [paragonie/constant_time_encoding#22]
https://twitter.com/FiloSottile/status/1157776085955878913

```
$b = Base64::decode('00==');
echo Base64::encode($b);
```

Outputs `0w==`

**Comment by kiamlaluno** [comment]
That is the same output of the following code.

```
$b = base64_decode("00==");
echo base64_encode($b);
```

It doesn't seem a bug of this library, if even the Base64 implementation of PHP 7.3 returns the same value.

**Comment by fkooman** [comment]
> It doesn't seem a bug of this library, if even the Base64 implementation of PHP 7.3 returns the same value.

Well, just because PHP's built-in functions acts a certain way doesn't mean that is the "proper" or expected way. As this library does not use PHP's built-in Base64 encoding this is not really relevant.

Whether or not this is _actually_ a problem would be a valid discussion... I don't consider myself qualified to have an opinion on this, that is why I linked to Filippo's Twitter post.
