### ISSUE TITLE
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in paragonie/constant_time_encoding/src/Binary.php on line 46c

### ISSUE THREAD

**Issue by rpelletierrefocus** [paragonie/constant_time_encoding#23]
The subject says it all, I am using the gelf-php project, which uses this as a depedency and I am getting this error.

PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in paragonie/constant_time_encoding/src/Binary.php on line 46c

**Comment by rpelletierrefocus** [comment]
My php version is 
PHP 5.6.31  and there is no possibility of upgrading it. I have a suspicion this is the issue. Is there any way aroung this.

**Comment by jdreesen** [comment]
You have to use version 1 of this library, because it supports PHP 5. Version 2 is PHP 7 only.

**Comment by rpelletierrefocus** [comment]
Saw that exactly 30 seconds after my second post. Should have read more closely. The 1.x branch indeed works great. Thank you.
