### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by mitmelon** [paragonie/constant_time_encoding#30]
Getting this error on console 

`libpng warning: iCCP: known incorrect sRGB profile`

 when using ParagonIE\ConstantTime\Encoding::hexEncode(random_bytes(16));

Please what are the ways to fix this.

**Comment by paragonie-security** [comment]
This is almost certainly not related to anything our code is doing. We don't touch libpng; that's a graphics library.
