### ISSUE TITLE
PHP Version support

### ISSUE THREAD

**Issue by marekdedic** [paragonie/constant_time_encoding#34]
Hi,
which version of this package can I use to support both PHP 5.6 and 8.x?

I am not happy about having to do that, however, I am creating a WordPress plugin so I have to support what WP supports :/

Thanks

**Comment by marekdedic** [comment]
I tried using `^1|^2` but that gets resolved when creating `composer.lock`, so that doesn't seem to be an option.

In case there currently is no version to support both, would you be willing to accept and publish a PR which adds at least rudimentary support for PHP up to 8.1 to v1? Thanks

**Comment by paragonie-security** [comment]
I'll update the v1.x branch to include 8 in the supported versions.

**Comment by paragonie-security** [comment]
This will be fixed in v1.1.0

**Comment by marekdedic** [comment]
Thank you!
