### ISSUE TITLE
Potential bug in recent release for `base32.decodeNoPadding`

### ISSUE THREAD

**Issue by HacKanCuBa** [paragonie/constant_time_encoding#44]
The improvement for #28 recently released apparently contains a bug:

![image](https://user-images.githubusercontent.com/7178420/173079947-be2d67bd-5bd4-4901-9dad-57864f9426b6.png)

https://github.com/paragonie/constant_time_encoding/compare/v2.5.0...v2.6.0#diff-267a11d22b48ca8dca6098fb78158b854362f5d98cfdc344de1f17c7d8b5da6bR199-R205

I think line 200 should have been `encodedString[$srcLen - $j]`.

**Comment by paragonie-security** [comment]
Yep. Good catch.
