### ISSUE TITLE
Base64::encode may return bool?

### ISSUE THREAD

**Issue by fkooman** [paragonie/constant_time_encoding#6]
https://github.com/paragonie/constant_time_encoding/blob/aa342bff0f39b72da79b62b72d95a9bb86aa80b9/src/Base64.php#L87

In which situation can this method return a bool?

**Comment by paragonie-scott** [comment]
It used to instead of throwing a `RangeException`. Now it always returns a string.

**Comment by paragonie-scott** [comment]
This is fixed in `2.1.0`. Thanks for letting me know about this. :)
