### ISSUE TITLE
Base64UrlSafe doesn't strip trailing =

### ISSUE THREAD

**Issue by kelunik** [paragonie/constant_time_encoding#9]
Base64Url doesn't have tailing `=` at the end, but `Base64UrlSafe::encode` produces those padding chars.

**Comment by paragonie-scott** [comment]
> Base64Url doesn't have trailing `=` at the end

[Yes it does](https://tools.ietf.org/html/rfc4648#page-8).

**Comment by paragonie-scott** [comment]
I've added an `encodeUnpadded()` method to the base32 and base64 classes, for requirements that don't conform strictly to RFC 4648, so developers don't feel tempted to just `rtrim($output, '=');` since it's unknown if `rtrim()` is cache-timing-safe.

**Comment by paragonie-scott** [comment]
New API methods are exposed in v2.2.0.
